### ISSUE TITLE
With Real rest API call

### ISSUE THREAD

**Issue by tarim** [thanhbinhtran93/react-state-management-movies-list#1]
Hi I like your implementation, but I have a question about the data. How do you want to add real rest API calls, please?

for example, when you open the page it will call rest api and get the list of movies( such as use useEffect etc)?

thank you,

**Comment by binhtran04** [comment]
Hi,

In the reducer, you can add one Action e.g. `loadInitialMovies` and the payload is an array of movies. In `MoviesProvider`, you can have a useEffect hook to make the API call to the backend. After the call succeeds, and you get the list of movies from, you can dispatch the `loadInitialMovies` action.
